name: RepositoryApp
packages:
  API:
    path: Packages/API
  SwiftDI:
    url: https://github.com/difomiry/SwiftDI
    branch: main
  Markdownosaur:
    url: https://github.com/difomiry/Markdownosaur
    branch: ios13
targets:
  App:
    platform: iOS
    type: application
    deploymentTarget: 13.0
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: io.github.difomiry.RepositoryApp.App
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
    preBuildScripts:
      - path: Scripts/SwiftFormat.sh
        name: SwiftFormat
        basedOnDependencyAnalysis: false
      - path: Scripts/SwiftLint.sh
        name: SwiftLint
        basedOnDependencyAnalysis: false
    dependencies:
      - package: API
      - package: SwiftDI
      - package: Markdownosaur
    sources:
      - path: Targets/App
        createIntermediateGroups: true
